export const DAILY_TIPS: string[] = [
  "Rotate crops like **eggplant** and **chili** with corn or legumes to prevent **Bacterial Wilt** build-up in the soil.",
  "Water your plants **early in the morning** so the leaves can dry during the day, reducing the risk of **fungal infections**.",
  "**Neem oil spray** is a great organic remedy for sucking pests. Mix 1 tbsp of neem oil with a few drops of mild soap in 1 liter of water.",
  "Prune the **lower leaves** of tomato plants to improve air circulation and prevent soil-borne pathogens from splashing onto the foliage.",
  "Healthy soil makes healthy plants. Add **organic compost** to boost your crops' natural resistance to pests and diseases.",
  "Avoid **overhead watering** for crops susceptible to **powdery mildew**. Apply water directly to the soil instead.",
  "**Yellow sticky traps** are excellent for monitoring whiteflies, aphids, and leafminers in your vegetable garden.",
  "**Marigolds** planted near your crops act as a natural pest deterrent and help keep harmful **nematodes** away from root systems.",
  "Ensure **proper spacing** between crops to allow air to flow, which dries leaves faster and prevents fungal outbreaks.",
  "If you spot **Anthracnose** on pepper fruits, immediately remove and dispose of the infected fruits. Do not compost them.",
  "Keep your **garden tools sanitized** using a 10% bleach solution or isopropyl alcohol to prevent spreading pathogens between plants.",
  "Adding **wood ash** to the soil around tomatoes and peppers provides calcium and potassium, reducing **blossom end rot**.",
  "For leafy greens, water-soluble fertilizers high in **nitrogen** promote lush, rapid growth. Apply every 10-14 days.",
  "**Mulch** the soil using clean straw or dried grass clippings to retain moisture, suppress weeds, and keep soil cool.",
  "Check the **undersides of leaves** weekly; pests like aphids, spider mites, and whiteflies love hiding there.",
  "If leaves look yellow but the veins remain green, your plant might be suffering from **iron chlorosis**. Check soil pH.",
  "**Diatomaceous earth** is a safe, organic powder that deters crawling insects. Sprinkle it on the soil around stems.",
  "Use a **drip irrigation system** to deliver water directly to plant roots, minimizing water loss and keeping foliage dry.",
  "**Fungal spores** thrive in high humidity. Water plants at their base rather than wetting the entire plant.",
  "Crop companion planting: plant **basil** next to tomatoes to enhance growth and repel hornworms, thrips, and flies.",
  "To control caterpillars organically, use **Bt (Bacillus thuringiensis)**, a naturally occurring soil bacterium targeting larvae.",
  "Conduct a **soil test** annually to check nutrient levels and adjust fertilizer application accordingly for maximum yield."
];
